---
dbvis_pkg: dbvis_linux_25_3_1.deb
dbvis_pkg_checksum: sha256:d7d36bde4b2fdb5f3d569837f8b639cb5983f95930729566bc215d045bb05dec
dbvis_url: https://www.dbvis.com/product_download/dbvis-25.3.1/media/{{ dbvis_pkg }}
